CREATE TABLE Accounts(
  id int AUTO_INCREMENT PRIMARY KEY,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  account_number VARCHAR(12),
  account_type VARCHAR(10),
  user_id int NOT NULL,
  balance DECIMAL(10, 2) NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES Users(id),
  check(balance>=0 AND LENGTH(account_number)=12)
);